const Items = [
  {
    id: 1,
    mainImage: "https://res.cloudinary.com/djogbntnb/image/upload/v1747220128/Screenshot_50_fbicbl.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699543/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-1_rmh7lp.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699548/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-2_p3chy5.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699706/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-3_uhtwa6.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682699802/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-4_p404nm.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682700118/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-5_mksj57.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682700238/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-6_jfndeo.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682700374/Blog%20Portfolio%20Gilbert/Project/msnproduction/img-7_uhh453.png",
    ],
    features: [
      "Dashboard with real-time stats",
      "Product & Inventory Management",
      "Customer & Supplier Modules",
      "Sales & Purchase Entry",
      "Invoice and Bill Generation",
      "Profit & Loss Reports",
      "User Roles and Permissions",
      "Responsive Design",
      "Error Handling (404 page, access control)",
    ],
    technologies: [
      "PHP",
      "Laravel",
      "MySQL",
      "Blade Templating",
      "Bootstrap",
      "jQuery",
      "Ajax",
    ],
    title: "Sales & Purchase Management System",
    description:
      "A complete Sales and Purchase Management System developed for PT. MULIA SEJATI NUSANTARA, designed to streamline product inventory, customer billing, and supplier transactions. Built with PHP (Laravel), it includes advanced reporting, invoicing, and real-time dashboard metrics to simplify day-to-day business operations. Supports multiple user roles with secured access.",
    category: "business",
    liveLink: "https://abjwork.com",
    codeLink: "https://github.com/BhushanPandagre/abjproject"
  },

  {
  id: 2,
  mainImage: "https://res.cloudinary.com/djogbntnb/image/upload/v1747220597/Screenshot_51_g0qaao.png",
  img: [
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701456/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-1_jppjdj.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701463/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-2_ptr4lg.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701467/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-3_gjle1m.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701479/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-4_kmaye9.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701489/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-5_nuhniv.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701492/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-6_rkvmhd.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701496/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-7_xjm4pm.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701499/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-8_dj0qoq.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701502/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-9_d1h5a0.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701505/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-10_kbbkd4.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1682701506/Blog%20Portfolio%20Gilbert/Project/mern-blog/img-11_mmspfs.png",
  ],
  features: [
    "Student Registration and Management",
    "Teacher and Staff Management",
    "Attendance Tracking (Daily/Monthly)",
    "Class, Subject and Exam Scheduling",
    "Grades & Report Card Generation",
    "Notice Board and Event Announcements",
    "Parent Portal Access",
    "Role-Based Access via Keycloak (Admin, Teacher, Student, Parent)",
    "Fee Management & Payment Tracking",
    "Login with Single Sign-On (SSO) using Keycloak",
    "Secure REST APIs for all modules",
    "Responsive Design",
    "404 Page and more.",
  ],
  technologies: [
    "React",
    "React Hooks",
    "Axios",
    "CSS",
    "NodeJS",
    "ExpressJS",
    "PostgreSQL",
    "Sequelize",
    "Keycloak",
    "Multer",
    "Nodemailer",
    "JWT",
    "Dotenv",
    "CORS",
  ],
  title: "School Management System",
  description:
    "A full-featured School Management System built with MERN stack and PostgreSQL for robust relational data handling. Integrated with Keycloak for secure role-based authentication (SSO). It supports all major functions required to manage a school such as student and teacher records, classes, exams, attendance, fees, announcements, and more. Designed to be scalable and secure for both small institutions and large campuses.",
  category: "education",
  liveLink: "https://ubuddy.billmex.com/login",
  codeLink: "https://github.com/BhushanPandagre"
},

  {
  id: 3,
  mainImage: "https://res.cloudinary.com/djogbntnb/image/upload/v1747221415/Screenshot_52_fouu4v.png",
  img: [
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312778/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-1_lcun2a.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312777/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-2_ar1fex.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312780/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-3_qpebgb.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312777/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-4_yadwtg.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312780/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-5_xvx0vj.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312773/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-6_aaq4yf.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312772/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-7_twij3j.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312773/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-8_njclct.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312774/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-9_zg1jfe.png",
    "https://res.cloudinary.com/du541igfh/image/upload/v1684312772/Blog%20Portfolio%20Gilbert/Project/mern-movie/img-10_yag7bj.png",
  ],
  features: [
    "Responsive landing page",
    "Company overview and About Us section",
    "Service listing (Web Development, Branding, Digital Marketing, etc.)",
    "Client Testimonials",
    "Contact form (Email-based)",
    "Interactive UI with animations",
    "SEO Optimized structure",
    "Live map integration",
    "Team section with photos & roles",
    "Newsletter subscription (Mailchimp or custom)",
    "404 page and many more",
    "Smooth scrolling and navigation",
    "Responsive Design",
  ],
  technologies: [
    "HTML",
    "CSS",
    "JavaScript",
    "Bootstrap",
    "GSAP",
    "Swiper.js",
    "EmailJS",
    "AOS (Animate on Scroll)",
    "Font Awesome",
    "Responsive Web Design Principles",
  ],
  title: "Company Website",
  description:
    "This is a modern and responsive static website for our company, showcasing services like web development, digital marketing, branding, and corporate identity. Built using core frontend technologies with a focus on performance, SEO, and usability. Includes interactive features such as animations, contact forms, and a services portfolio to help attract clients and present our brand professionally.",
  category: "business",
  liveLink: "https://www.mexdy.com/",
  codeLink: "https://github.com/BhushanPandagre"
},

 
  {
    id: 4,
    mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-1_yhedpu.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-2_uktrxk.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-3_s1js9i.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683869747/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-4_sb9ga6.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683869748/Blog%20Portfolio%20Gilbert/Project/mern-student-management-system/img-5_wrxlr7.png",
    ],
    features: [
      "Add Student",
      "Edit Student",
      "Remove Student",
      "No Student Page",
      "Responsive Design",
      "404 Page and many more",
    ],
    technologies: [
      "React",
      "React Hooks",
      "React Router Dom",
      "Axios",
      "Bootstrap",
      "React Icons",
      "Sweet Alert2",
      "Node JS",
      "Express JS",
      "Cors",
      "Mongoose",
      "Dotenv",
      "Nodemon",
      "MongoDB",
    ],
    title: "Student Management System",
    description:
      "Fullstack open source student management system application made with MongoDB, Express, React & Nodejs (MERN)",
    category: "business",
    liveLink: "#",
 codeLink: "https://github.com/BhushanPandagre"
  },
 
  {
    id: 5,
    mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-1_gqero4.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-2_ukjdh2.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944695/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-3_t6uxoj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-4_btevir.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-5_oakjx2.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944092/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-6_pqefy9.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1682944091/Blog%20Portfolio%20Gilbert/Project/bert-quiz/img-7_wfrvb7.png",
    ],
    features: [
      "User registration and login",
      "Select the type of question and the difficulty level of the question",
      "Juis time is running and after the time is up it stops automatically",
      "The final results of the answers answered will be shown",
      "Incorrect and correct answer results will be displayed",
      "Responsive Design",
    ],
    technologies: [
      "React",
      "React Vite",
      "Tailwind CSS",
      "Firebase Authentication",
      "Framer Motion",
      "React Firebase Hooks",
      "React Icons",
    ],
    title: "Bert Quiz",
    description:
      "Fullstack open source quiz application",
    category: "personal",
    liveLink: "#",
 codeLink: "https://github.com/BhushanPandagre"
  },
  {
    id: 6,
    mainImage: "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
    img: [
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-1_q5d6pn.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033411/Blog%20Portfolio%20Gilbert/Project/shopify/img-2_nko9ic.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033413/Blog%20Portfolio%20Gilbert/Project/shopify/img-3_rnhbr1.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-4_ks8lck.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033409/Blog%20Portfolio%20Gilbert/Project/shopify/img-5_eotroj.png",
      "https://res.cloudinary.com/du541igfh/image/upload/v1683033408/Blog%20Portfolio%20Gilbert/Project/shopify/img-6_fgpzef.png",
    ],
    features: [
      "Mobile Responsive",
      "Beautiful Animations",
      "Product",
      "Pricing",
      "Testimonial",
      "Contact",
    ],
    technologies: [
      "React",
      "React Vite",
      "Tailwind CSS",
      "Framer Motion",
      "React Icons",
      "React Hooks",
    ],
    title: "Shopify",
    description:
      "Open source landing page shopify application",
    category: "personal",
    liveLink: "#",
 codeLink: "https://github.com/BhushanPandagre"
  },
];

export default Items;
